#! /bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
YELLOW='\033[0;93m'



function die() {
  printf "\n${RED}${@}${NC}\n"
  exit 1
}

function donemsg() {
  sleep 2
  printf "\e[93m${GREEN}DONE!${NC}\n"
  sleep 1
}

function install_homebrew() {
  printf "installing homebrew\n"
  sleep 1
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  donemsg
}

function install_ruby() {
  printf "installing ruby\n"
  sleep 1
  brew install rbenv ruby-build
  donemsg
}

function install_zsh() {
  printf "installing oh-my-zsh\n"
  sleep 1
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  sleep 1
  chsh -s /bin/zsh
  donemsg
}

# TODO: Need to configure zsh

function install_node() {
  printf "installing node and yarn\n"
  sleep 1
  brew install node
  donemsg
}

function install_vscode() {
  printf "installing vscode\n"
  sleep 1
  brew install visual-studio-code --cask
  donemsg
}

function install_docker() {
  printf "installing docker\n"
  sleep 1
  brew install docker --cask
  unset DOCKER_HOST
  donemsg
}

function install_other() {
  printf "installing other tools\n"
  sleep 1
  brew install typora --cask
  brew install slack --cask
  brew install ack
  brew install wget
  defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
  defaults write dev.warp.Warp-Stable "ApplePressAndHoldEnabled" -bool false
  defaults write com.apple.dock autohide-delay -float 0; killall Dock
  donemsg
}

function create_env() {
  # setup dev env
  printf "Creating Developer directories\n"
  sleep 1
  mkdir $HOME/Developer
  mkdir $HOME/Developer/github.com
  mkdir $HOME/Developer/github.com/nateleavitt
  mkdir $HOME/Developer/github.com/loyalstream
  donemsg
}

function move_files() {
  # move dotfiles
  printf "moving dotfiles to hidden\n"
  mv $HOME/dotfiles ~/.dotfiles
  # Add <strong>.old</strong> to any existing Vim file in the home directory
  sleep 1
  printf "renaming old dirs to *.old if exist\n"
  sleep 1
  for i in $HOME/.vim \
    $HOME/.vimrc \
    $HOME/.gvimrc \
    $HOME/.gvimrc.before \
    $HOME/.gvimrc.after \
    $HOME/.vimrc.before \
    $HOME/.vimrc.after \
    $HOME/.gitignore_global \
    $HOME/.hyper.js \
    $HOME/.zshrc \
    $HOME/.oh-my-zsh/custom/aliases.zsh \
    $HOME/.oh-my-zsh/custom/completions.zsh \
    $HOME/.oh-my-zsh/custom/exports.zsh; do
    # $HOME/Library/Application\ Support/Code/User/settings.json; do
    if [[ ( -e $i ) || ( -h $i ) ]]; then
      echo "${i} has been renamed to ${i}.old"
      mv "${i}" "${i}.old" || die "Could not move ${i} to ${i}.old"
    fi
  done
  donemsg
}

function config_files() {
  # Remove and replace .vimrc.before after files
  printf "setting up vim and configuring git\n"
  sleep 1
  ln -s $HOME/.dotfiles/vim $HOME/.vim
  ln -s $HOME/.dotfiles/vim/vimrc $HOME/.vimrc
  ln -s $HOME/.dotfiles/vim/gvimrc $HOME/.gvimrc
  ln -s $HOME/.dotfiles/vim/gvimrc.before $HOME/.gvimrc.before
  ln -s $HOME/.dotfiles/vim/gvimrc.after $HOME/.gvimrc.after
  ln -s $HOME/.dotfiles/vim/vimrc.before $HOME/.vimrc.before
  ln -s $HOME/.dotfiles/vim/vimrc.after $HOME/.vimrc.after
  ln -s $HOME/.dotfiles/git/gitignore_global $HOME/.gitignore_global
  ln -s $HOME/.dotfiles/zsh/zshrc $HOME/.zshrc
  ln -s $HOME/.dotfiles/zsh/custom/aliases.zsh $HOME/.oh-my-zsh/custom/aliases.zsh
  ln -s $HOME/.dotfiles/zsh/custom/completions.zsh $HOME/.oh-my-zsh/custom/completions.zsh
  ln -s $HOME/.dotfiles/zsh/custom/exports.zsh $HOME/.oh-my-zsh/custom/exports.zsh
  # ln -s $HOME/.dotfiles/vscode/settings.json $HOME/Library/Application\ Support/Code/User/
  donemsg
}

function config_git() {
  printf  "Configuring global git ignore\n"
  sleep 1
  git config --global core.excludesfile ~/.gitignore_global
  # git config --global credential.helper osxkeychain
  git config --global pager.branch false
  donemsg
}

function install_vim_plugins() {
  printf "downloading and configuring vim plugins\n"
  sleep 1
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
  vim +PluginInstall +qall
  donemsg
}

function install_font() {
  printf "installing SF Mono font\n"
  sleep 1
  cp font/*.otf $HOME/Library/Fonts/
  domemsg
}

# INSTALL
printf "\n"
printf "*******************************************************\n"
printf "${GREEN}Welcome to nateleavitt's OSX setup script${NC}\n"
printf "*******************************************************\n"
sleep 3
# install_homebrew
move_files
config_files
install_ruby
install_zsh
install_node
install_vscode
# install_docker
install_other
create_env
config_git
install_vim_plugins
sleep 2
printf "*******************************************************\n"
printf "${GREEN}Everything is now setup!${NC}\n"
sleep 2
printf "\n"
printf "Let me know if you have any questions:\n"
printf "https://github.com/nateleavitt/dotfiles\n"
printf "e[93 ${GREEN}Thank you!${NC}\n"
printf "*******************************************************\n"
printf "\n"

