#! /bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
YELLOW='\033[0;93m'



function die() {
  printf "\n${RED}${@}${NC}\n"
  exit 1
}

function donemsg() {
  sleep 2
  printf "${GREEN}DONE!${NC}\n"
  sleep 1
}

function update_apt() {
  printf "updating apt\n"
  sleep 1
  sudo apt update
  donemsg 
}

function install_prereqs() {
  printf "installing prereqs..."
  {
    # Required for rbenv and ruby
    sudo apt -y install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev libpq-dev
    # Required for vscode
    sudo apt -y install apt-transport-https
    # Required for docker
    sudo apt -y install ca-certificates

    # Required for capslock to esc key
    # https://askubuntu.com/questions/1059663/remapping-caps-lock-to-escape-in-ubuntu-18-04-bionic
    # sudo apt -y install gnome-tweak-tool
    # Gnome Tweaks -> Keyboard & Mouse -> Additional Layout Options -> Caps Lock key behavior.

    sudo apt -y install wget
    sudo apt -y install vim
    sudo apt -y install ack
    sudo apt -y install gdebi
  } &> /dev/null
  donemsg
}

function install_zsh() {
  printf "installing oh-my-zsh..."
  {
    sudo apt -y install zsh
    sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
  } &> /dev/null
  chsh -s $(which zsh)
  donemsg
}

function move_files() {
  # move dotfiles
  printf "moving dotfiles to hidden..."
  mv $HOME/dotfiles ~/.dotfiles &> /dev/null
  donemsg
  printf "renaming old dirs to *.old if exist..."
  sleep 1
  {
    for i in $HOME/.vim \
      $HOME/.vimrc \
      $HOME/.gvimrc \
      $HOME/.gvimrc.before \
      $HOME/.gvimrc.after \
      $HOME/.vimrc.before \
      $HOME/.vimrc.after \
      $HOME/.gitignore_global \
      $HOME/.zshrc \
      $HOME/.config/Code/User/settings.json; do
      if [[ ( -e $i ) || ( -h $i ) ]]; then
        echo "${i} has been renamed to ${i}.old"
        mv "${i}" "${i}.old" || die "Could not move ${i} to ${i}.old"
      fi
    done
  } &> /dev/null
  donemsg
}

function config_files() {
  # Remove and replace .vimrc.before after files
  printf "setting up configuration files..."
  sleep 1
  {
    ln -s $HOME/.dotfiles/vim $HOME/.vim
    ln -s $HOME/.dotfiles/vim/vimrc $HOME/.vimrc
    ln -s $HOME/.dotfiles/vim/gvimrc $HOME/.gvimrc
    ln -s $HOME/.dotfiles/vim/gvimrc.before $HOME/.gvimrc.before
    ln -s $HOME/.dotfiles/vim/gvimrc.after $HOME/.gvimrc.after
    ln -s $HOME/.dotfiles/vim/vimrc.before $HOME/.vimrc.before
    ln -s $HOME/.dotfiles/vim/vimrc.after $HOME/.vimrc.after
    ln -s $HOME/.dotfiles/git/gitignore_global $HOME/.gitignore_global
    ln -s $HOME/.dotfiles/zsh/zshrc $HOME/.zshrc
    ln -s $HOME/.dotfiles/zsh/custom/aliases.zsh $HOME/.oh-my-zsh/custom/aliases.zsh
    ln -s $HOME/.dotfiles/zsh/custom/completions.zsh $HOME/.oh-my-zsh/custom/completions.zsh
    ln -s $HOME/.dotfiles/zsh/custom/exports.zsh $HOME/.oh-my-zsh/custom/exports.zsh
    # ln -s $HOME/.dotfiles/vscode/settings.json $HOME/.config/Code/User/settings.json
    ln -s $HOME/.dotfiles/vscode/settings.json /mnt/c/Users/natel/AppData/Roaming/Code/User/settings.json
    ln -s $HOME/.dotfiles/wsl/wslconfig /mnt/c/Users/natel/.wslconfig
  } &> /dev/null
  donemsg
}

function install_node() {
  printf "installing node and yarn..."
  {
    sudo apt -y install node
    sudo apt -y install npm
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt -y update
    sudo apt -y install yarn
  } &> /dev/null
  donemsg
}

function install_postgres() {
  printf "installing other postgresql..."
  {
    # Install postgres
    sudo apt -y install postgresql postgresql-contrib
  } &> /dev/null
  donemsg
}

function create_env() {
  # setup dev env
  printf "Creating code directories..."
  sleep 2
  {
    mkdir -p $HOME/Code
    mkdir -p $HOME/Code/github.com
    mkdir -p $HOME/Code/github.com/nateleavitt
    mkdir -p $HOME/Code/github.com/loyalstream
    mkdir -p $HOME/.config/Code/User
  } &> /dev/null
  donemsg
}

function install_ruby() {
  printf "installing rbenv..."
  {
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.zshrc
    echo 'eval "$(rbenv init -)"' >> ~/.zshrc
    git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
  } &> /dev/null
  donemsg
}

function config_git() {
  printf  "Configuring global git ignore..."
  sleep 1
  git config --global core.excludesfile ~/.gitignore_global &> /dev/null
  donemsg
}

function install_vim_plugins() {
  printf "downloading and configuring vim plugins..."
  sleep 1
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim &> /dev/null
  vim +PluginInstall +qall
  donemsg
}

function remove_packages() {
  printf "cleaning up and removing old packages..."
  sleep 1
  sudo apt -y autoremove &> /dev/null
  donemsg
}

# INSTALL
printf "\n"
printf "*******************************************************\n"
printf "${GREEN}Welcome to nateleavitt's Linux setup script${NC}\n"
printf "*******************************************************\n"
sudo apt -y update &> /dev/null
install_prereqs
install_zsh
move_files
config_files
install_node
install_postgres
create_env
install_ruby
config_git
install_vim_plugins
remove_packages
sleep 2
printf "*******************************************************\n"
printf "${GREEN}Everything is now setup!${NC}\n"
# might want to output: https://github.com/Microsoft/vscode/issues/23991
sleep 1
printf "\n"
printf "Let me know if you have any questions:\n"
printf "https://github.com/nateleavitt/dotfiles\n"
printf "${GREEN}Thank you!${NC}\n"
printf "*******************************************************\n"
printf "\n"

