#! /bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color


function die() {
    echo "\n${RED}${@}${NC}\n"
    exit 1
}

function donemsg() {
  sleep 2
  printf "\n"
  printf "${GREEN}done!${NC}\n"
  sleep 1
}

function install_homebrew() {
  echo -n "installing homebrew"
  sleep 1
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" \
    || die "Had problems installing Homebrew"
  donemsg
}

function install_ruby() {
  echo "installing ruby\n"
  sleep 1
  brew install rbenv ruby-build
  donemsg
}

function install_zsh() {
  echo "installing oh-my-zsh\n"
  sleep 1
  git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
  sleep 1
  chsh -s /bin/zsh
  donemsg
}

# TODO: Need to configure zsh

function install_node() {
  echo "installing node and yarn\n"
  sleep 1
  brew install node
  brew install yarn
  donemsg
}

function install_vscode() {
  echo "installing vscode\n"
  sleep 1
  brew cask install visual-studio-code
  donemsg
}

function install_docker() {
  echo "installing docker\n"
  sleep 1
  brew cask install docker
  donemsg
}

function install_other() {
  echo "installing other tools\n"
  sleep 1
  brew cask install hyper
  brew cask install typora
  brew cask install google-chrome
  brew cask install 1password
  brew cask install slack
  brew install ack
  brew install wget
  donemsg
}

function create_env() {
  # setup dev env
  echo "Creating code directories\n"
  sleep 1
  mkdir $HOME/Code
  mkdir $HOME/Code/github.com
  mkdir $HOME/Code/github.com/nateleavitt
  mkdir $HOME/Code/github.com/loyalstream
  donemsg
}

function move_files() {
  # move dotfiles
  echo "moving dotfiles to hidden\n"
  mv $HOME/dotfiles ~/.dotfiles
  # Add <strong>.old</strong> to any existing Vim file in the home directory
  sleep 1
  echo "renaming old dirs to *.old if exist\n"
  sleep 1
  for i in $HOME/.vim \
    $HOME/.vimrc \
    $HOME/.gvimrc \
    $HOME/.gvimrc.before \
    $HOME/.gvimrc.after \
    $HOME/.vimrc.before \
    $HOME/.vimrc.after \
    $HOME/.gitignore_global \
    $HOME/.oh-my-zsh/custom/aliases.zsh \
    $HOME/.oh-my-zsh/custom/completions.zsh \
    $HOME/.oh-my-zsh/custom/exports.zsh \
    $HOME/.zshrc; do
    if [[ ( -e $i ) || ( -h $i ) ]]; then
      echo "${i} has been renamed to ${i}.old"
      mv "${i}" "${i}.old" || die "Could not move ${i} to ${i}.old"
    fi
  done
  donemsg
}

function config_vim() {
  # Remove and replace .vimrc.before after files
  echo "setting up vim and configuring git\n"
  sleep 1
  ln -s $HOME/.dotfiles/vim $HOME/.vim
  ln -s $HOME/.dotfiles/vim/vimrc $HOME/.vimrc
  ln -s $HOME/.dotfiles/vim/gvimrc $HOME/.gvimrc
  ln -s $HOME/.dotfiles/vim/gvimrc.before $HOME/.gvimrc.before
  ln -s $HOME/.dotfiles/vim/gvimrc.after $HOME/.gvimrc.after
  ln -s $HOME/.dotfiles/vim/vimrc.before $HOME/.vimrc.before
  ln -s $HOME/.dotfiles/vim/vimrc.after $HOME/.vimrc.after
  ln -s $HOME/.dotfiles/git/gitignore_global $HOME/.gitignore_global
  ln -s $HOME/.dotfiles/zsh/zshrc $HOME/.zshrc
  ln -s $HOME/.dotfiles/zsh/custom/aliases.zsh $HOME/.oh-my-zsh/custom/aliases.zsh
  ln -s $HOME/.dotfiles/zsh/custom/completions.zsh $HOME/.oh-my-zsh/custom/completions.zsh
  ln -s $HOME/.dotfiles/zsh/custom/exports.zsh $HOME/.oh-my-zsh/custom/exports.zsh
  donemsg
}

function config_git() {
  echo  "Configuring global git ignore\n"
  sleep 1
  git config --global core.excludesfile ~/.gitignore_global
  git config --global credential.helper osxkeychain
  donemsg
}

function install_vim_plugins() {
  echo "downloading and configuring vim plugins\n"
  sleep 1
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
  vim +PluginInstall +qall
  donemsg
}

# INSTALL
printf "\n"
printf "${GREEN}Welcome to nateleavitt's OSX setup script${NC}\n"
sleep 3
install_homebrew
install_ruby
install_zsh
install_node
install_vscode
install_docker
install_other
create_env
move_files
config_vim
config_git
install_vim_plugins
sleep 2
printf "${GREEN}Everything is now setup!${NC}\n"
sleep 2
printf "\n"
printf "Let me know if you have any questions: https://github.com/nateleavitt/dotfiles\n"
printf "Thank you!\n"
printf "\n"
