#! /bin/bash
usage() { echo "Usage: $0 [-r <boolean>] [-b <boolean>] [-m <boolean>] [-e <string>" 1>&2; exit 1; }

brew=true;
rvm=true;
mvim=true;

while getopts ":r:b:m:e:" o; do
  case "${o}" in
    r)
      rvm=${OPTARG}
      ;;
    b)
      brew=${OPTARG}
      ;;
    m)
      mvim=${OPTARG}
      ;;
    e)
      email=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "${rvm}" ] || [ -z "${brew}" ] || [ -z "${mvim}" ] || [ -z "${email}" ]; then
  usage
fi

function die() {
    echo "${@}"
    exit 1
}

function install_rvm() {
  echo "installing rvm stable"
  gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  bash -s stable < <(curl -sSL https://get.rvm.io) \
    || die "Had problems installing RVM"
}

function install_homebrew() {
  echo "installing Homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" \
    || die "Had problems installing Homebrew"
}

function install_mvim() {
  echo "installing mvim"
  brew install macvim --with-lua
  brew linkapps macvim

}

# move dotfiles
echo 'moving dotfiles to hidden'
mv $HOME/dotfiles ~/.dotfiles


# Add <strong>.old</strong> to any existing Vim file in the home directory
for i in $HOME/bin $HOME/.vim $HOME/.vimrc $HOME/.vimrc.before $HOME/.vimrc.after \
  $HOME/.gvimrc $HOME/.gvimrc.before $HOME/.gvimrc.after $HOME/.bashrc \
  $HOME/.bash_profile $HOME/.config/fish $HOME/.ssh; do
  if [[ ( -e $i ) || ( -h $i ) ]]; then
    echo "${i} has been renamed to ${i}.old"
    mv "${i}" "${i}.old" || die "Could not move ${i} to ${i}.old"
  fi
done

echo "install fish"
brew install fish

# Adding bash environment files
echo "creating bash environment files"
# ln -s $HOME/.dotfiles/bash/bashrc $HOME/.bashrc
# ln -s $HOME/.dotfiles/bash/bash_profile $HOME/.bash_profile
# ln -s $HOME/.dotfiles/bash/git-completion.bash $HOME/.git-completion.bash
ln -s $HOME/.dotfiles/fish $HOME/.config/fish

echo "configuring ssh environment"
ln -s $HOME/.dotfiles/ssh $HOME/.ssh
ssh-keygen -t rsa -C $email


# echo "source bash files - you may need to do it manually"
# source $HOME/.bashrc
# source $HOME/.bash_profile

if $rvm ; then install_rvm ; fi
if $brew ; then install_homebrew ; fi
if $mvim ; then install_mvim ; fi


# Remove and replace .vimrc.before after files
echo "linking default gvimrc and vimrc files if installed"
ln -s $HOME/.dotfiles/vim $HOME/.vim
ln -s $HOME/.dotfiles/vim/vimrc $HOME/.vimrc
ln -s $HOME/.dotfiles/vim/gvimrc $HOME/.gvimrc
ln -s $HOME/.dotfiles/vim/gvimrc.before $HOME/.gvimrc.before
ln -s $HOME/.dotfiles/vim/gvimrc.after $HOME/.gvimrc.after
ln -s $HOME/.dotfiles/vim/vimrc.before $HOME/.vimrc.before
ln -s $HOME/.dotfiles/vim/vimrc.after $HOME/.vimrc.after
ln -s $HOME/.dotfiles/bin $HOME

echo "downloading and configuring vim plugins"
git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

echo "Launching fish shell"
fish
echo "Finished!"
